### ISSUE TITLE
Seems to be broken after oobabooga updated exllamav2 to 0.0.12

### ISSUE THREAD

**Issue by jepjoo** [SoylentMithril/BrainHackingChip#4]
Was working fine earlier today before updating. After updating I'm getting this:

```
Traceback (most recent call last):
  File "G:\ooba\modules\text_generation.py", line 426, in generate_reply_custom
    for reply in shared.model.generate_with_streaming(question, state):
  File "G:\ooba\extensions\BrainHackingChip\exllamav2.py", line 118, in hijack_generate_with_streaming
    self.generator.begin_stream(ids, settings, loras=self.loras)
  File "G:\ooba\installer_files\env\Lib\site-packages\exllamav2\generator\streaming.py", line 90, in begin_stream
    assert gen_settings.cfg_scale is not None, "No CFG scale set"
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: No CFG scale set
Output generated in 0.00 seconds (0.00 tokens/s, 0 tokens, context 35, seed 887093545)
```

**Comment by SoylentMithril** [comment]
Ok, I have a tentative fix up. Let me know if that solves the issue

**Comment by jepjoo** [comment]
All good now, thanks!
